# DS1 문제 6

In [1]:
import pandas as pd
import numpy as np


In [95]:
df = pd.read_csv('data/birth_risk',delimiter=',')
df.head()

weight  visits  smoke immature plural  amniotic_fluid  parturition  \
0  68.934240      12  False    37주이상     한명           False        False   
1  88.435374       9  False    37주이상     한명           False        False   
2  78.911565       9  False    37주이상     한명           False        False   
3  72.562358       9   True    37주미만     한명           False        False   
4  77.097506      14  False    37주이상     한명           False        False   

   breech  glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  
0   False       False          False          False     False     8    False  
1   False       False          False          False     False     2    False  
2   False       False          False          False     False     1    False  
3   False       False          False          False     False     7    False  
4   False       False          False          False     False    10    False

In [96]:
df['immature']=pd.get_dummies(df['immature'],drop_first=True)

df.head()

weight  visits  smoke  immature plural  amniotic_fluid  parturition  \
0  68.934240      12  False         1     한명           False        False   
1  88.435374       9  False         1     한명           False        False   
2  78.911565       9  False         1     한명           False        False   
3  72.562358       9   True         0     한명           False        False   
4  77.097506      14  False         1     한명           False        False   

   breech  glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  
0   False       False          False          False     False     8    False  
1   False       False          False          False     False     2    False  
2   False       False          False          False     False     1    False  
3   False       False          False          False     False     7    False  
4   False       False          False          False     False    10    False

In [101]:
pd.get_dummies(df['plural'])

세쌍둥이이상  쌍둥이  한명
0           0    0   1
1           0    0   1
2           0    0   1
3           0    0   1
4           0    0   1
5           0    0   1
6           0    0   1
7           0    0   1
8           0    0   1
9           0    1   0
10          0    0   1
11          0    0   1
12          0    0   1
13          0    0   1
14          0    0   1
15          0    0   1
16          0    0   1
17          0    0   1
18          0    0   1
19          0    0   1
20          0    0   1
21          0    0   1
22          0    0   1
23          0    0   1
24          0    0   1
25          0    1   0
26          0    0   1
27          0    0   1
28          0    0   1
29          0    0   1
...       ...  ...  ..
24970       0    0   1
24971       0    0   1
24972       0    1   0
24973       0    0   1
24974       0    0   1
24975       0    0   1
24976       0    0   1
24977       0    1   0
24978       0    0   1
24979       0    1   0
24980       0    0   1
24981       0    1   0
24982       0    0   1
24983       0    0   1
24984       0    0   1
24985       0    0   1
24986       0    0   1
24987       0    0   1
24988       0    0   1
24989       0    0   1
24990       0    0   1
24991       0    0   1
24992       0    0   1
24993       0    0   1
24994       0    0   1
24995       0    0   1
24996       0    0   1
24997       0    0   1
24998       0    1   0
24999       0    1   0

[25000 rows x 3 columns]

In [108]:
df[['plural1','plural2','plural3']]=pd.get_dummies(df['plural'])
df.head()

weight  visits  smoke  immature plural  amniotic_fluid  parturition  \
0  68.934240      12  False         1     한명           False        False   
1  88.435374       9  False         1     한명           False        False   
2  78.911565       9  False         1     한명           False        False   
3  72.562358       9   True         0     한명           False        False   
4  77.097506      14  False         1     한명           False        False   

   breech  glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  \
0   False       False          False          False     False     8    False   
1   False       False          False          False     False     2    False   
2   False       False          False          False     False     1    False   
3   False       False          False          False     False     7    False   
4   False       False          False          False     False    10    False   

   plural1  plural2  plural3  
0        0        0        1  
1        0        0        1  
2        0        0        1  
3        0        0        1  
4        0        0        1

In [109]:
df = df.drop('plural3',axis=1)
df = df.drop('plural',axis=1)

In [110]:
df.head()

weight  visits  smoke  immature  amniotic_fluid  parturition  breech  \
0  68.934240      12  False         1           False        False   False   
1  88.435374       9  False         1           False        False   False   
2  78.911565       9  False         1           False        False   False   
3  72.562358       9   True         0           False        False   False   
4  77.097506      14  False         1           False        False   False   

   glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  plural1  \
0       False          False          False     False     8    False        0   
1       False          False          False     False     2    False        0   
2       False          False          False     False     1    False        0   
3       False          False          False     False     7    False        0   
4       False          False          False     False    10    False        0   

   plural2  
0        0  
1        0  
2        0  
3        0  
4        0

In [111]:
df.describe()

weight        visits      immature          xgrp       plural1  \
count  25000.000000  25000.000000  25000.000000  25000.000000  25000.000000   
mean      67.545732     11.170960      0.885640      5.062560      0.001600   
std       14.593923      4.022027      0.318254      3.159621      0.039969   
min       33.560091      0.000000      0.000000      0.000000      0.000000   
25%       56.689342      9.000000      1.000000      2.000000      0.000000   
50%       64.399093     11.000000      1.000000      5.000000      0.000000   
75%       76.190476     13.000000      1.000000      8.000000      0.000000   
max      170.068027     49.000000      1.000000     10.000000      1.000000   

            plural2  
count  25000.000000  
mean       0.031240  
std        0.173969  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [35]:
Q1 = 56.689342  
Q3 = 76.190476
IQR = (Q3 - Q1 )*1.5
IQR

29.251701

In [112]:
df1=df[(df['weight']>= (Q1-IQR)) & ( df['weight'] <=(Q3+IQR))]
len(df1)

24636

In [113]:
df1.head()

weight  visits  smoke  immature  amniotic_fluid  parturition  breech  \
0  68.934240      12  False         1           False        False   False   
1  88.435374       9  False         1           False        False   False   
2  78.911565       9  False         1           False        False   False   
3  72.562358       9   True         0           False        False   False   
4  77.097506      14  False         1           False        False   False   

   glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  plural1  \
0       False          False          False     False     8    False        0   
1       False          False          False     False     2    False        0   
2       False          False          False     False     1    False        0   
3       False          False          False     False     7    False        0   
4       False          False          False     False    10    False        0   

   plural2  
0        0  
1        0  
2        0  
3        0  
4        0

In [137]:
train=df1[df1['xgrp']<=5]
test=df1[df1['xgrp']>=6]

In [141]:
train_X=train.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,13,14]]
train_y=train.iloc[:,12]

In [142]:
train_y.head()

1    False
2    False
6    False
7    False
8    False
Name: at_risk, dtype: bool

In [143]:
test_X= test.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,13,14]]
test_y=test.iloc[:,12]

In [122]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial')


In [172]:
clf=model.fit(train_X,train_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [173]:
np.exp(clf.coef_)

array([[1.00604044, 0.9671203 , 1.16042581, 0.47322422, 1.46570774,
        0.99913809, 1.32821763, 0.83973521, 1.04611075, 1.04636706,
        1.04259488, 1.73931482, 1.28341794]])

In [146]:
1/(1+np.exp(result.coef_.sum()))

0.31024581980301535

In [124]:
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'multinomial',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': 0,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [177]:
x1=model.predict_proba(test_X)

In [175]:
test_y

0        False
3        False
4        False
5        False
9         True
10       False
11       False
14       False
15       False
20       False
22       False
24       False
25       False
26       False
27       False
30       False
35       False
36       False
38       False
43       False
45       False
46       False
47       False
54       False
57       False
58       False
60       False
61       False
63       False
64       False
         ...  
24930    False
24932    False
24935    False
24937    False
24940    False
24942    False
24946    False
24948    False
24955    False
24956    False
24957    False
24959    False
24965    False
24966    False
24968    False
24973    False
24974    False
24975    False
24978    False
24980    False
24981    False
24983    False
24985    False
24986    False
24989    False
24991    False
24994    False
24997    False
24998    False
24999    False
Name: at_risk, Length: 11315, dtype: bool

In [189]:
np.where(x1[:,1]>

array([0.00993068, 0.07149774, 0.00958853, ..., 0.01364731, 0.02182437,
       0.00294355])

In [148]:
# 정확도 확인
from sklearn.metrics import accuracy_score
print(accuracy_score(predict1, test_y))

0.9840919133893062


In [149]:
test_X.head(3)

weight  visits  smoke  immature  amniotic_fluid  parturition  breech  \
0  68.934240      12  False         1           False        False   False   
3  72.562358       9   True         0           False        False   False   
4  77.097506      14  False         1           False        False   False   

   glycosuria  chypertension  phypertension  gestosis  plural1  plural2  
0       False          False          False     False        0        0  
3       False          False          False     False        0        0  
4       False          False          False     False        0        0

In [150]:
sample = [[59,8,False,0,False,False,True,False,False,False,False,0,1]]
sample

[[59, 8, False, 0, False, False, True, False, False, False, False, 0, 1]]

In [151]:
model.predict(sample)

array([False])

In [157]:
model.predict_proba(sample)

array([[0.86889677, 0.13110323]])

In [162]:
test_prob=model.predict_proba(test_X)

In [165]:
result = np.where(test_prob>=0.02,1,0)

In [171]:
result[:,1].sum()

2069

In [73]:
from sklearn import metrics

In [76]:
print(metrics.classification_report(test_y, predict1))

              precision    recall  f1-score   support

       False       0.98      1.00      0.99     11135
        True       0.00      0.00      0.00       180

   micro avg       0.98      0.98      0.98     11315
   macro avg       0.49      0.50      0.50     11315
weighted avg       0.97      0.98      0.98     11315



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
