In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/birth_risk")
df.head()

weight  visits  smoke immature plural  amniotic_fluid  parturition  \
0  68.934240      12  False    37주이상     한명           False        False   
1  88.435374       9  False    37주이상     한명           False        False   
2  78.911565       9  False    37주이상     한명           False        False   
3  72.562358       9   True    37주미만     한명           False        False   
4  77.097506      14  False    37주이상     한명           False        False   

   breech  glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  
0   False       False          False          False     False     8    False  
1   False       False          False          False     False     2    False  
2   False       False          False          False     False     1    False  
3   False       False          False          False     False     7    False  
4   False       False          False          False     False    10    False

In [3]:
df.describe()

weight        visits          xgrp
count  25000.000000  25000.000000  25000.000000
mean      67.545732     11.170960      5.062560
std       14.593923      4.022027      3.159621
min       33.560091      0.000000      0.000000
25%       56.689342      9.000000      2.000000
50%       64.399093     11.000000      5.000000
75%       76.190476     13.000000      8.000000
max      170.068027     49.000000     10.000000

In [4]:
a = 56.689342 - (1.5 *(76.190476 -56.689342))
b = 76.190476 + (1.5 *(76.190476 -56.689342))
print(a)
print(b)

27.437641000000003
105.442177


In [5]:
df = df[(df.weight>=a)&(df.weight<=b)]

In [6]:
len(df) # 5 번 답 24636

24636

In [7]:
df["immature"] = pd.get_dummies(df.immature, drop_first = True)

In [8]:
df[["plural_1","plural_2", "plural_3"]] = pd.get_dummies(df.plural)

In [9]:
df = df.drop("plural_3", axis = 1)
df = df.drop("plural", axis = 1)

In [10]:
df.head()

weight  visits  smoke  immature  amniotic_fluid  parturition  breech  \
0  68.934240      12  False         1           False        False   False   
1  88.435374       9  False         1           False        False   False   
2  78.911565       9  False         1           False        False   False   
3  72.562358       9   True         0           False        False   False   
4  77.097506      14  False         1           False        False   False   

   glycosuria  chypertension  phypertension  gestosis  xgrp  at_risk  \
0       False          False          False     False     8    False   
1       False          False          False     False     2    False   
2       False          False          False     False     1    False   
3       False          False          False     False     7    False   
4       False          False          False     False    10    False   

   plural_1  plural_2  
0         0         0  
1         0         0  
2         0         0  
3         0         0  
4         0         0

In [11]:
train_set = df[df.xgrp<=5]
test_set = df[df.xgrp>=6]

In [12]:
train_set = train_set.drop("xgrp" , axis = 1)
test_set = test_set.drop("xgrp" , axis = 1)

In [29]:
train_set.tail(10)

weight  visits  smoke  immature  amniotic_fluid  parturition  \
24979   59.863946      13  False         0           False         True   
24982   81.632653       3  False         1           False        False   
24984   48.979592       0  False         0           False        False   
24987   68.027211       9  False         1           False        False   
24988   72.562358      15  False         1           False        False   
24990  102.040816      12  False         1           False        False   
24992   50.793651      14  False         1           False        False   
24993   52.154195      11  False         1           False        False   
24995   80.272109      14  False         1           False        False   
24996   68.934240       6   True         1           False        False   

       breech  glycosuria  chypertension  phypertension  gestosis  at_risk  \
24979   False       False          False          False     False    False   
24982   False       False          False          False     False    False   
24984   False       False          False          False     False    False   
24987    True       False          False          False     False    False   
24988   False       False          False          False     False    False   
24990   False       False          False          False     False    False   
24992   False        True          False          False     False    False   
24993   False       False          False          False     False    False   
24995   False       False          False          False     False    False   
24996   False       False          False          False     False    False   

       plural_1  plural_2  
24979         0         1  
24982         0         0  
24984         0         0  
24987         0         0  
24988         0         0  
24990         0         0  
24992         0         0  
24993         0         0  
24995         0         0  
24996         0         0

In [30]:
train_Y =  train_set["at_risk"]
train_x = train_set.drop("at_risk", axis = 1)

In [31]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(train_x, train_Y)

print(clf.coef_)
print(np.exp(clf.coef_))

[[ 0.0079669  -0.07313422  0.25689281 -1.51535383  0.74550553 -0.04956182
   0.53206604 -0.32505549  0.09775232  0.09582417  0.08284563  1.04102135
   0.49183658]]
[[1.00799872 0.92947607 1.29290653 0.21973042 2.10750657 0.95164632
  1.702446   0.72248726 1.10268964 1.10056554 1.08637409 2.83210811
  1.63531686]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [32]:
sample = [[59,8,False, 0,False,False,True, False,False,False,False, 0,1]]

In [33]:
clf.predict(sample)

array([False])

In [34]:
print(clf.predict(sample))
clf.predict_proba(sample)

[False]


array([[0.8637861, 0.1362139]])

In [35]:
test_set.head()

weight  visits  smoke  immature  amniotic_fluid  parturition  breech  \
0  68.934240      12  False         1           False        False   False   
3  72.562358       9   True         0           False        False   False   
4  77.097506      14  False         1           False        False   False   
5  72.108844      13  False         1           False        False    True   
9  58.956916       8  False         0           False        False    True   

   glycosuria  chypertension  phypertension  gestosis  at_risk  plural_1  \
0       False          False          False     False    False         0   
3       False          False          False     False    False         0   
4       False          False          False     False    False         0   
5       False          False          False     False    False         0   
9       False          False          False     False     True         0   

   plural_2  
0         0  
3         0  
4         0  
5         0  
9         1

In [36]:
test_y =  test_set["at_risk"]
test_x = test_set.drop("at_risk", axis = 1)

In [50]:
test_prob = clf.predict_proba(test_x)

In [62]:
clf.predict(test_x)

array([False, False, False, ..., False, False, False])

In [63]:
test_prob

array([[0.9900457 , 0.0099543 ],
       [0.9295104 , 0.0704896 ],
       [0.99081521, 0.00918479],
       ...,
       [0.98649188, 0.01350812],
       [0.98033761, 0.01966239],
       [0.99752382, 0.00247618]])

In [64]:
test_prob_y = np.where(test_prob>=0.02,1,0)

In [65]:
test_prob_y

array([[1, 0],
       [1, 1],
       [1, 0],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]])

In [55]:
predict = test_prob_y[:,1]

In [66]:
print(predict)
print(len(predict))

[0 1 0 ... 0 0 0]
11315


In [67]:
import sklearn.metrics as skm
print(skm.precision_score(test_y,predict))

0.04477611940298507


In [68]:
print(skm.roc_auc_score(test_y,predict))

0.6692448735219279


In [71]:
df.to_csv?

In [72]:
df.to_csv("data/output.csv", index=False)